name: FakeElytra
description: Allows you to glide without an Elytra.
version: 1.2.1-SNAPSHOT
api-version: 1.17
author: AMDBartek
website: https://github.com/AMDBartek/FakeElytra/
main: com.amdbartek.FakeElytra.FakeElytra

permissions:
  fakeelytra.glide:
    default: op

commands:
  glide:
    description: Glide without an Elytra (toggle).
    usage: /glide
    permission: fakeelytra.glide